badgeLabel = "beta"
footerNotice = "© ArchiUnit. ABN: 44 791 776 896."
contactEmail = "info@archiunit.com"
mediaBaseURL = "//uploads.archiunit.com/"
youtubePromoVideoId = "lxvRRN7eDgc"
facebookLikeButtonAppId = "1769835703334213"
paypalDonateButtonId = "UBBXRTGUJ7KCW"
