badgeLabel = "beta"
footerNotice = "© ArchiUnit. ABN: 44 791 776 896."
contactEmail = "info@archiunit.com"
mediaBaseURL = "//uploads.archiunit.com/"
youtubePromoVideoId = "lxvRRN7eDgc"
facebookLikeButtonAppId = "1769835703334213"
paypalDonateButtonId = "UBBXRTGUJ7KCW"
mapboxAccessToken = "pk.eyJ1IjoiamF6YWFyY2hpdW5pdCIsImEiOiJjamF4N2E5YTIwdWw5MndvOXdmaWhqeXYyIn0.J35m1o69rg4LC0a9cLffng"
